Added Top Category Section in the Home Page
smaranjitghose/indokhaadyam pull request #22
Opened 2022-02-07 13:22 UTC by manishbajagai2

@smaranjitghose Finally the work's been done. Please Check it out #3 

### Screenshot : 
![image](https://user-images.githubusercontent.com/62448303/152795930-7a616b0b-d30d-40cc-8c16-598c8d17dee8.png)

2022-02-07 15:33 UTC, smaranjitghose requested changes

2022-02-07 15:33 UTC, smaranjitghose commented on src/components/Categories.js
> +        <div className="row">
Please define the headings and image paths ina separate JSON variable

2022-02-07 15:33 UTC, smaranjitghose commented
@anushbhatia  could you assist him the vercel deployment issue due to the warnings, please?

2022-02-07 15:41 UTC, smaranjitghose requested changes

2022-02-07 15:41 UTC, smaranjitghose commented on src/components/Categories.js
> +import "../../node_modules/bootstrap/dist/css/bootstrap.min.css";
Please use react-bootstrap: https://react-bootstrap.github.io/getting-started/introduction/

2022-02-07 15:46 UTC, smaranjitghose requested changes

2022-02-07 15:46 UTC, smaranjitghose commented on src/styles/categories.css
> +
Could you please follow the structure of files requested [here](https://github.com/smaranjitghose/indokhaadyam/issues/12)

2022-02-07 15:46 UTC, smaranjitghose commented on src/components/Categories.js
> +            <img src="https://i.postimg.cc/jSmq3c6Z/main-Course.jpg"/>
- All images should be placed inside `assets/categories/`
- Prefer using images from Unsplash (in webp format perhaps)

2022-02-07 17:35 UTC, anushbhatia commented on src/components/Categories.js
> +            <img src="https://i.postimg.cc/qRXkRdP5/chaat.jpg"/>
Do add alt text everywhere where you have added images this might solve deployment issue.

2022-02-16 09:04 UTC, anushbhatia commented
Any updates @manishbajagai2 ?

2022-02-23 16:11 UTC, closed without merging