updated UI of footer
smaranjitghose/indokhaadyam pull request #24
Opened 2022-02-08 07:16 UTC by whiteHatpro

fixed issue #16

2022-02-08 07:19 UTC, whiteHatpro commented
@anushbhatia please review the pr

2022-02-08 16:02 UTC, anushbhatia requested changes
don't add package-lock.json
just check the .gitignore if that file is ignored

2022-02-08 16:04 UTC, anushbhatia reviewed
also remove unused background images that are added.
A suggestion food related image would add a better look to the current website

2022-02-09 13:47 UTC, whiteHatpro commented
@anushbhatia ok will do it asap

2022-02-09 14:09 UTC, whiteHatpro commented
@anushbhatia i have done the changes as requested by you

2022-02-09 17:57 UTC, smaranjitghose requested changes

2022-02-09 17:57 UTC, smaranjitghose commented on package-lock.json
> +      "resolved": "https://registry.npmjs.org/@gar/promisify/-/promisify-1.1.2.tgz",
Remove this file from your commit please

2022-02-09 17:57 UTC, smaranjitghose commented on src/App.js
> +
Avoid unnecessary formatting  changes like black spaces as much as possible

2022-02-09 17:57 UTC, smaranjitghose commented on src/scss/_colors.scss
> +// color variables used in the app.
Nice work segregating this!

2022-02-09 17:57 UTC, smaranjitghose commented on src/githublogo/github.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="feather feather-github" viewBox
Should be inside assets

2022-02-09 17:57 UTC, smaranjitghose commented on src/components/Footer/footer.module.scss
> +	background-image: url("./footer/brooke.jpg");
should be present inside assets

2022-02-09 17:57 UTC, smaranjitghose commented on src/components/Footer/Footer.jsx
> +						{emoji("Made with ❤️ in India for the students of the world.")}
Made with ❤️ in India for the foodies around the globe

2022-02-09 17:58 UTC, smaranjitghose commented
Change the text color to make it distinct from the background image please

2022-02-09 20:09 UTC, whiteHatpro commented
@smaranjitghose done the changes

2022-02-09 20:30 UTC, whiteHatpro commented
@smaranjitghose @anushbhatia its working fine in my local machine
i don't know why there is an deployment issue.

2022-02-10 09:09 UTC, anushbhatia commented
> @smaranjitghose @anushbhatia its working fine in my local machine i don't know why there is an deployment issue.

is there any warnings when you run the project do eliminate them if there are any?

2022-02-10 14:41 UTC, whiteHatpro commented
> > @smaranjitghose @anushbhatia its working fine in my local machine i don't know why there is an deployment issue.
> 
> is there any warnings when you run the project do eliminate them if there are any?

@anushbhatia there is no warnings and it is compiled successfully

2022-02-10 14:44 UTC, whiteHatpro commented
@anushbhatia please look at the terminal

![Screenshot (113)](https://user-images.githubusercontent.com/77486870/153431092-45870f6a-dd6a-4fed-ae9f-cf73a908be71.png)

![Screenshot (114)](https://user-images.githubusercontent.com/77486870/153431104-64afe5ac-b490-4f5e-8200-71444e984087.png)

2022-02-13 12:31 UTC, anushbhatia commented
> @anushbhatia please look at the terminal
> 
> ![Screenshot (113)](https://user-images.githubusercontent.com/77486870/153431092-45870f6a-dd6a-4fed-ae9f-cf73a908be71.png)
> 
> ![Screenshot (114)](https://user-images.githubusercontent.com/77486870/153431104-64afe5ac-b490-4f5e-8200-71444e984087.png)

recreate this pr with latest code

2022-02-15 14:16 UTC, closed without merging