🚀  feat: Added Teams Page
smaranjitghose/indokhaadyam pull request #25
Opened 2022-02-08 13:31 UTC by Aniket-508

![screencapture-localhost-3000-2022-02-08-18_58_11](https://user-images.githubusercontent.com/71957423/152997151-9f91a0b0-431a-446f-9714-b31a369ae50c.png)

2022-02-08 13:31 UTC, Aniket-508 commented
@anushbhatia @smaranjitghose Please checkout this PR!

2022-02-08 18:09 UTC, anushbhatia requested changes
Could you check the why deployment is failing

1. Might be some warnings left
2. Unused variables present.

2022-02-08 18:09 UTC, anushbhatia commented on src/App.js
> +      {/* <GlobalStyle />
create a new page using routing in this.

2022-02-13 11:55 UTC, Aniket-508 commented
@anushbhatia The routing actually has to be implemented differently in the navbar which is another issue.

2022-02-16 09:03 UTC, anushbhatia commented on src/App.js
>  import Home from "./components/Home";
comment home,global style, footer out and your deployment will work fine

2022-02-18 16:27 UTC, merged