issue #14 to top button added
smaranjitghose/indokhaadyam pull request #27
Opened 2022-02-14 07:09 UTC by ronitblenz

I have added the to top button which automatically scrolls to the top when clicked
{Smooth Animation Added}

Kindly merge my PR
(JWOC-MEDIUM)

Thanks

2022-02-14 13:50 UTC, ronitblenz commented
Plz check my PR

2022-02-15 08:21 UTC, anushbhatia requested changes
Don't attach the package-lock.json file in the code, please. Check the gitignore once if it's present there.

2022-02-15 11:31 UTC, ronitblenz commented
I made the change you wanted, plz check and merge my PR

2022-02-15 17:57 UTC, anushbhatia commented on src/components/scroll/ScrollToTop.js
> +import { isVisible } from "@testing-library/user-event/dist/utils";
add this library too in the package.json i think because of this depolyment is failing

2022-02-16 08:54 UTC, anushbhatia requested changes
2 unused libraries are present because of which warnings are generated and your vercel deployment is failing
 `isVisible`, `BiWindows` kindly remove them if none of them are used

2022-02-23 16:11 UTC, closed without merging