Added Contact Page and did routing for the same
smaranjitghose/indokhaadyam pull request #28
Opened 2022-02-15 14:13 UTC by Priiyaa

closes issue #18

2022-02-15 17:50 UTC, anushbhatia requested changes
Add padding inside the form placeholder elements
I would recommend using bootstrap elements for this so that responsiveness can be handeled too along side this

2022-02-15 17:50 UTC, anushbhatia commented on src/App.js
> +          <Route exact path="/user/register" element={<ContactForm />} />
please use /contact

2022-02-16 16:42 UTC, Priiyaa commented on src/App.js
> +          <Route exact path="/user/register" element={<ContactForm />} />
ok got it!

2022-02-16 17:03 UTC, Priiyaa commented
### Added padding
**Mobile View**
![contact mobile view](https://user-images.githubusercontent.com/76914418/154317258-82a81b7b-7aeb-440c-b7a8-d495cc11fde2.jpg)
**Laptop and Tab view**

![contact3](https://user-images.githubusercontent.com/76914418/154317385-3e6156d5-08bf-4166-b566-4874bc694117.jpg)

2022-02-16 17:04 UTC, Priiyaa commented
I have changed the route to /user/contact

2022-02-16 17:42 UTC, anushbhatia requested changes
change the route path to /contact only

2022-02-16 18:11 UTC, Priiyaa commented
> change the route path to /contact only

Done!

2022-02-17 18:52 UTC, merged