Updated Footer Design
smaranjitghose/indokhaadyam pull request #9
Opened 2022-01-27 14:18 UTC by Shruti025

2022-01-29 03:25 UTC, smaranjitghose requested changes

2022-01-29 03:25 UTC, smaranjitghose commented on src/components/Footer.js
> +<link href="https://fonts.googleapis.com/css2?family=Bitter:wght@600&family=Roboto+Mono:wght@500&family=Varela+Round&display=swap" rel="stylesheet"></link>
For now, limit the usage of fonts to Poppins and Montserrat please

2022-01-29 03:25 UTC, smaranjitghose commented on src/components/Footer.js
> +/*const Container = styled.div`
Remove any code that is redundant

2022-01-29 03:25 UTC, smaranjitghose commented on src/components/Footer.js
> +    background: rgb(255,204,17);
It would be great if you can have variables for each color defined separately such as :
```footer-bag: rgb(255,204,17)```

2022-01-29 03:25 UTC, smaranjitghose commented on src/components/Footer.js
> +                <p style = {{fontFamily: "monospace"}}>Made with 💖 in India for the world</p>
This text can also be declared in a global variable

2022-01-30 20:45 UTC, Shruti025 commented
hey @smaranjitghose , do I need to close this pull request before making a new one?

2022-01-31 04:49 UTC, anushbhatia approved these changes

2022-02-01 17:43 UTC, Shruti025 commented
hey @smaranjitghose @anushbhatia, are there any changes required in this PR before merging?

2022-02-01 19:07 UTC, merged